name: Web-doc GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        env:
          ACCESS_TOKEN: ACCESS_TOKEN
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm run build
